# to replicate -> conda env create --file environment.yml
name: SisRecomendacionPy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - ipykernel
  - pandas
  - scikit-learn
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - numpy
  - scipy
  - statsmodels
  - python=3.12.4